apiVersion: v2
name: github-actions-runner
description: A Helm chart for Kubernetes

type: application

version: 0.5.2
appVersion: 0.9.3

kubeVersion: ">=1.19.0"

home: https://github.com/fullstack-devops/helm-charts/tree/main/charts/github-actions-runner
sources:
  - https://github.com/fullstack-devops/github-actions-runner
  - https://quay.io/repository/fullstack-devops/github-actions-runner

maintainers:
  - name: eksrha
    email: ekrsha@outlook.de
    url: https://github.com/eksrha
